### ISSUE TITLE
Does this Module have function to delete specific objects, per say a computer?

### ISSUE THREAD

**Issue by awhy1957** [Bill-Stewart/PowerShell-DRADelegation#1]
just want to be able to delete a spe

**Comment by Bill-Stewart** [comment]
The purpose of this module is to provide cmdlets to manage the DRA delegation model, not to create/update/remove AD objects. To manage AD objects using DRA, use the DRA PowerShell module (`NetIQ.DRA.PowerShellExtensions`).

**Comment by awhy1957** [comment]
![no powershell module](https://github.com/Bill-Stewart/PowerShell-DRADelegation/assets/111225844/6ef68b2c-7bff-4c80-94a1-1b760b344cc1)

Sorry, do you know how I can acquire the PS module?

**Comment by Bill-Stewart** [comment]
It is a component you can install with DRA. Contact OpenText support if you need help with that.
